# Generated by Django 6.0.5 on 2026-05-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la tâche')),
                ('due_date', models.DateField(verbose_name='Date')),
                ('due_time', models.TimeField(verbose_name='Heure')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['due_date', 'due_time'],
            },
        ),
        migrations.CreateModel(
            name='VoiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(blank=True, help_text='Laissez vide pour utiliser la voix par défaut du système.', max_length=500, verbose_name='ID de la voix')),
                ('rate', models.IntegerField(default=150, help_text='Mots par minute (défaut: 150)', verbose_name='Vitesse')),
                ('volume', models.FloatField(default=1.0, help_text='Entre 0.0 et 1.0', verbose_name='Volume')),
            ],
            options={
                'verbose_name': 'Configuration vocale',
                'verbose_name_plural': 'Configuration vocale',
            },
        ),
    ]
