# Generated by Django 6.0.5 on 2026-05-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceconfig',
            name='pitch',
            field=models.IntegerField(default=100, help_text='Tonalite de la voix (80-125, profil naturel).', verbose_name='Tonalite'),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='pre_alarm_text',
            field=models.CharField(blank=True, default='Attention', help_text='Texte lu avant le nom de la tache.', max_length=200, verbose_name='Texte pre-alarme'),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='repeat_count',
            field=models.PositiveSmallIntegerField(default=1, help_text='Nombre de lectures de la tache (1-5).', verbose_name='Nombre de repetitions'),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='repeat_interval_seconds',
            field=models.PositiveSmallIntegerField(default=1, help_text='Pause en secondes entre deux lectures (0-10).', verbose_name='Pause entre repetitions'),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='use_system_fallback',
            field=models.BooleanField(default=True, help_text='Utilise spd-say/espeak si pyttsx3 echoue.', verbose_name='Activer fallback systeme'),
        ),
    ]
