# Generated by Codex on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_voiceconfig_pitch_voiceconfig_pre_alarm_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceconfig',
            name='audio_gain',
            field=models.FloatField(default=1.2, help_text='Amplification du lecteur audio premium (1.0 a 3.0).', verbose_name='Gain audio'),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='neural_voice_id',
            field=models.CharField(default='fr-FR-DeniseNeural', help_text='Voix Microsoft Edge TTS utilisee quand edge-tts est installe.', max_length=100, verbose_name='Voix neurale francaise'),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='play_attention_sound',
            field=models.BooleanField(default=True, help_text='Joue un court signal avant la lecture vocale lorsque le systeme le permet.', verbose_name="Son d'attention"),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='tts_engine',
            field=models.CharField(choices=[('auto', 'Automatique: voix premium puis fallback'), ('neural', 'Voix neurale premium'), ('pyttsx3', 'pyttsx3 hors ligne'), ('system', 'Moteur systeme')], default='auto', help_text="Automatique utilise d'abord une voix neurale francaise si disponible.", max_length=20, verbose_name='Moteur vocal'),
        ),
    ]
